/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavBar: typeof import('./src/components/AppNavBar.vue')['default']
    AppSnackbar: typeof import('./src/components/AppSnackbar.vue')['default']
    Crud: typeof import('./src/components/Crud.vue')['default']
    CrudCategoria: typeof import('./src/components/CrudCategoria.vue')['default']
    CrudProduto: typeof import('./src/components/CrudProduto.vue')['default']
    CrudTable: typeof import('./src/components/CrudTable.vue')['default']
    CrudTableCategoria: typeof import('./src/components/CrudTableCategoria.vue')['default']
    CrudTableProduto: typeof import('./src/components/CrudTableProduto.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
