/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/categoria': RouteRecordInfo<'/categoria', '/categoria', Record<never, never>, Record<never, never>>,
    '/categorias': RouteRecordInfo<'/categorias', '/categorias', Record<never, never>, Record<never, never>>,
    '/produto': RouteRecordInfo<'/produto', '/produto', Record<never, never>, Record<never, never>>,
    '/produtos': RouteRecordInfo<'/produtos', '/produtos', Record<never, never>, Record<never, never>>,
  }
}
